### ISSUE TITLE
Include the latest versions, not only the older ones

### ISSUE THREAD

**Issue by lmakarov** [caskroom/homebrew-versions#1144]
I want to hardcore a particular version of Vagrant and VirtualBox in an install/update script. This way I can make sure there won't be any unexpected version changes.
Currently this is not possible, since only older versions of packages are available via hombrew-version.
It would be really useful to have the latest/current versions included as well. Thanks!

**Comment by vitorgalvao** [comment]
> only older versions of packages are available via hombrew-version.

That is incorrect. We also have betas and nightlies.

> It would be really useful to have the latest/current versions included as well.

That also causes a lot of overhead for us maintainers, and makes this repo more of a mess than it already is. You can simply create [a tap](https://github.com/Homebrew/homebrew/blob/master/share/doc/homebrew/brew-tap.md), you don’t need us to host casks for the versions you need.
