### ISSUE TITLE
Localised Firefox beta casks need to be moved away from versioned URLs if possible

### ISSUE THREAD

**Issue by fanquake** [caskroom/homebrew-versions#1251]

**Comment by vitorgalvao** [comment]
Why? What’s wrong with being versioned?

**Comment by fanquake** [comment]
It would only be to handle updating. None of the Firefox-Lang casks are
versioned.

**Comment by vitorgalvao** [comment]
The reverse should happen, then. The non-beta casks should be versioned, as we currently prefer to have versions.

**Comment by fanquake** [comment]
Fixed
