### ISSUE TITLE
Unable to update

### ISSUE THREAD

**Issue by williamboman** [caskroom/homebrew-versions#1261]
Looks like a rewrite was done on the `master` branch

```sh
$ brew update --verbose
[...]
==> git rev-parse -q --verify HEAD
4480fe4f12eeacf55d6f628898f3abcb9099e32a
git config core.autocrlf false
git pull --ff --no-rebase origin refs/heads/master:refs/remotes/origin/master
From https://github.com/caskroom/homebrew-versions
 ! [rejected]        master     -> origin/master  (non-fast-forward)
Error: Failed to update tap: caskroom/versions
[...]
```

**Comment by williamboman** [comment]
Yep,

```sh
$ pwd
/usr/local/Library/Taps/caskroom/homebrew-versions
$ git fetch
From https://github.com/caskroom/homebrew-versions
 + 4480fe4...47159ca master     -> origin/master  (forced update)
```

```
Your branch and 'origin/master' have diverged,
and have 2737 and 2738 different commits each, respectively.
```

Holee shit.

**Comment by vitorgalvao** [comment]
Thank you for the notice. Easiest solution is to `brew untap caskroom/versions && brew tap caskroom/versions`, and no harm done.

However, this shouldn’t be happening. Judging from the affected cask and the recent history, @fanquake have you done the rewrite?

**Comment by williamboman** [comment]
>However, this shouldn’t be happening. Judging from the affected cask and the recent history, @fanquake have you done the rewrite?

Yeah, and the extremity of the diverge is pretty worrisome.

I simply did a `$ git fetch && git reset --hard @{u}`, I suppose that's safe as well?

**Comment by vitorgalvao** [comment]
> I simply did a `$ git fetch && git reset --hard @{u}`, I suppose that's safe as well?

Whatever works. Since the tap only holds casks, there shouldn’t be any repercussions regarding usage, so whichever solution you pick is fine, as long as it fixes it.

**Comment by fanquake** [comment]
@vitorgalvao No, the commit modifying the emacs cask was done through the GitHub UI. So a rewrite shouldn't have happened.

**Comment by vitorgalvao** [comment]
Thank you. If any of @caskroom/maintainers did it, please do tell so we can confirm it came from user error and not github (wouldn’t be the first time we see github acting weirdly with commits), in which case we should report it. Something similar seems to have happened in the taps fonts.

No need to keep the issue open, though.

**Comment by robertd** [comment]
This worked for me `brew untap caskroom/versions && brew update && brew cleanup --force -s && sudo rm -rf "$(brew --cache)" && brew tap caskroom/versions`

**Comment by callahad** [comment]
On my end I'm seeing the divergence at https://github.com/caskroom/homebrew-versions/commit/d7f9062917ed5ff7bb7bfee8b3bdfd9ceb482711

`master` used to have https://github.com/caskroom/homebrew-versions/commit/28a022ba6e9cc0ff22e82000d1828715cdb11e31 follow it, but now I see https://github.com/caskroom/homebrew-versions/commit/8c415de2f34c684e058f5d03b7597f1b186d3df7 instead.

The change to the formula is the same, but the commit message was rewritten from:

    Add TrueCrypt 7.1a

To:

     iQEcBAABAgAGBQJTi6fyAAoJEMUNS2x+QKQJYPoH/RngGb1BSrcB6VrT8JGKv2kS
     urv3zL9GnYvGKv4R78kU0bLLq8Iknh5okxp4EOAQqMsHAUSLWKSCDv+84PE981rs
     ivhez2zHC0IIRzCBS3heXRPFtTpfIJWcDIhau4w5iAaLo/EIXd7SWBUBKvkGwbZ6
     a11tK8uJXTqXjDWDitWZYO01SxmCkCwA/6xp04ZS0ThSWc2iURvwVbrUS1rL7iMQ
     Jwe/WCY5emmX6EkcONa0kIUuK4Jeu3J7WMxliAS5fLZGEYkQHLjmFhzJShjIC/YB
     1wwaatrvHb1wVNtSsX07xLw11Jdi9Re50tzP2CtJ3j/SbcoFI67sPRiu48j0tag=
     =L/fU
     -----END PGP SIGNATURE-----

    Add TrueCrypt 7.1a

**Comment by victorpopkov** [comment]
I think that it's me you have to blame, because I recently have overwritten the email address in some of my commits and have pushed by mistake to `upstream/master` instead of the `origin/master`. I apologize for all the inconvenience and troubles caused by this action. However, I'm sure that only my commits were affected.

There is no way to express how sorry I'm if that was me who caused so many troubles, but I've noticed that only recently. :bow:

**Comment by mcnesium** [comment]
`brew untap caskroom/versions && brew tap caskroom/versions` fixed it for me, so no worries. thx for the good work.

**Comment by margaritis** [comment]
Confirming that `brew untap caskroom/versions && brew tap caskroom/versions` fixes the issue.

**Comment by jaredsburrows** [comment]
@vitorgalvao Thank you!

**Comment by timmolter** [comment]
`brew untap caskroom/versions && brew tap caskroom/versions` fixed it for me too.

**Comment by hsiaoyi0504** [comment]
I fixed the same problem by just using `brew update`
