### ISSUE TITLE
Royaltsx checksum errors.

### ISSUE THREAD

**Issue by Asshad** [caskroom/homebrew-versions#1378]
Hi there,

I have been trying to get this but encountered with checksum errors. I guess you may need to update the hash. Thanks.

bash$ brew cask install royal-tsx-beta
==> Downloading http://v2.royaltsx.com/updates/royaltsx_2.2.0.1000.dmg
######################################################################## 100.0%
==> Note: running "brew update" may fix sha256 checksum errors
Error: sha256 mismatch
Expected: 4f46388d574cc4b4bcc8881b5fdb086d0c8ea47a6cc5563ebe6cc4a84795d363
Actual: e547054b6ce818d1429701804069d0aec7c5e494f9b757e2068093bb6ca4c9a2
File: /Library/Caches/Homebrew/royal-tsx-beta-2.2.0.1000.dmg
To retry an incomplete download, remove the file above.

**Comment by adityadalal924** [comment]
Fixed in #1379
