### ISSUE TITLE
Add tap documentation

### ISSUE THREAD

**Issue by adityadalal924** [caskroom/homebrew-versions#1517]
We should have a link to https://github.com/Homebrew/homebrew/blob/master/share/doc/homebrew/How-to-Create-and-Maintain-a-Tap.md to point users to as an alternative when we refuse Casks here due to it not fitting in our new rules.

**Comment by vitorgalvao** [comment]
[We do](https://github.com/caskroom/homebrew-versions#acceptable-casks) (third paragraph).
