### ISSUE TITLE
Clarify use of language codes

### ISSUE THREAD

**Issue by Zirro** [caskroom/homebrew-versions#1529]
There does not appear to be a consistent method for naming casks in alternative languages. Mozilla and Tor use [IETF language tags](https://en.wikipedia.org/wiki/IETF_language_tag), occasionally including region codes when distributing their software. In casks, these have been inconsistently shortened to two characters. See for example:
* [firefox-cn.rb](https://github.com/caskroom/homebrew-versions/blob/master/Casks/firefox-cn.rb)
* [firefox-tw.rb](https://github.com/caskroom/homebrew-versions/blob/master/Casks/firefox-tw.rb)
* [torbrowser-zh.rb](https://github.com/caskroom/homebrew-versions/blob/master/Casks/torbrowser-zh.rb)

In the first two, the region code was selected for the two letters. In most other language casks, letters indicating language were chosen instead.

We should define a consistent standard for handling language codes and rename existing casks as required.

**Comment by vitorgalvao** [comment]
> We should define a consistent standard for language codes and rename existing casks as required.

Agreed. What do you suggest such standard to be?

**Comment by Zirro** [comment]
If adding another dash to the name is acceptable, always using full names such as "firefox-zh-cn", "firefox-ja-jp" and "firefox-en-gb" allows for both codes. It may be troublesome if an application does not declare a specific region, however.

**Comment by Zirro** [comment]
Per the rule suggested above, I believe these are the changes that should be made to existing casks:

* adobe-reader-pt -> adobe-reader-pt-br
* battle-net-cn -> battle-net-zh-cn
* firefox-beta-cn -> firefox-beta-zh-cn
* firefox-beta-gb -> firefox-beta-en-gb
* firefox-cn -> firefox-zh-cn
* firefox-esr-cn -> firefox-esr-zh-cn
* firefox-pt -> firefox-pt-br
* firefox-tw -> firefox-zh-tw
* hearthstone-eu -> hearthstone-en-gb
* openoffice-pt -> openoffice-pt-pt
* thunderbird-cn -> thunderbird-zh-cn
* thunderbird-pt -> thunderbird-pt-br
* torbrowser-zh -> torbrowser-cn

Other casks which only exist in one version at the host have will be left untouched with just their language code.

**Comment by vitorgalvao** [comment]
Sounds good. Just those, though? Is every other one already correct according to those rules?

Care to draft a PR so we can also discuss with the other maintainers? I doubt there will be objections. Make it one commit per cask, please.

**Comment by Zirro** [comment]
>Just those, though?

I think so, but I would not mind a check being performed by second pair of eyes. Most casks were already using ISO-639-1 letters and only a few languages seem to warrant different versions.

I'll get the PR done later this week.

**Comment by Zirro** [comment]
I've noted that the documentation added in caskroom/homebrew-cask#16221 mentions that both codes should be added when available, but I believe this is unnecessary. In my pull request I have added both codes only when regional versions within the same language are distributed at the host. Provided that we choose this solution, the documentation ought to be updated to reflect this.

When double-checking the proposed changes, I noticed that adobe-reader-pt seems to be the download made available for both regions, and therefore left it unchanged despite the download url which contains "pt_BR".

**Comment by vitorgalvao** [comment]
> mentions that both codes should be added when available, but I believe this is unnecessary.

The problem with making such judgement is different users will make different assumptions. Since maintainers do not know everything about every app, we’ll invariably merge inconsistencies.

This is why strict rules are set, so we have something to measure correctness against.

> When double-checking the proposed changes, I noticed that the current adobe-reader-pt seems to be the only download available for this language despite the "pt_BR" in the download url. For this reason I left it unchanged.

Which is why it must be `pt_BR` in this case. For one, it already prepares for an eventual `pt_PT`, but more importantly it is consistent and makes the rule easily understandable to someone that comes later.

**Comment by vitorgalvao** [comment]
Closing since https://github.com/caskroom/homebrew-cask/pull/16221.
