### ISSUE TITLE
Trouble with uninstall :input

### ISSUE THREAD

**Issue by larsschwegmann** [caskroom/homebrew-versions#1557]
Hello!

I'm trying to add the beta of [Gutenprint](http://gimp-print.sourceforge.net/MacOSX.php) to caskroom/versions.
The Gutenprint installer disk image contains the installer .pkg and an uninstall script.
The script needs to be run as root and requires the user to type "Y" and hit enter.
The Cask file doc says that there is an :input array containing lines sent to stdin of the process.

I've tried to set the array to `['Y']`, `['Y\n']` and `['Y^'J]` but none of these seem to work.
The script works fine when I use it manually in the shell.

Here is my code:

```Ruby
cask 'gutenprint-beta' do
  version '5.2.11-pre2'
  sha256 '3d42cf662b7311adf53a0ecfa4fdf978ea76e86317c15925ec0bb056d1d9579e'

  url "http://downloads.sourceforge.net/project/gimp-print/gutenprint-#{version.major_minor}/#{version}/gutenprint-#{version}.dmg"
  name 'Gutenprint'
  homepage 'http://gimp-print.sourceforge.net/MacOSX.php'
  license :gpl 

  pkg "gutenprint-#{version}.pkg"

  uninstall :script => 'uninstall-gutenprint.command',
            :input => ['Y^J']
end

```

Any help is appreciated!

Btw: Although this is the beta version of Gutenprint, it's the only version working on the latest Mac OS X. The latest stable version only works on Yosemite. Is caskroom/versions the right place for the beta?

Thanks!

**Comment by vitorgalvao** [comment]
> Btw: Although this is the beta version of Gutenprint, it's the only version working on the latest Mac OS X. The latest stable version only works on Yosemite. Is caskroom/versions the right place for the beta?

[No](https://github.com/caskroom/homebrew-cask/blob/master/CONTRIBUTING.md#but-there-is-no-stable-version). Please submit the cask (as a PR) to the main repo, explain the issue again, and we’ll take it from there.
