### ISSUE TITLE
Can't install iterm2-beta

### ISSUE THREAD

**Issue by ronaldsuwandi** [caskroom/homebrew-versions#1738]
Hi,

Tried to install iterm2-beta and it complained about bad header file
```
~ ☕️  brew cask install iterm2-beta
Error: Cask 'iterm2-beta' definition is invalid: Bad header line: '{:v1=>"iterm2-beta"}' does not match file name
~ ☕️  brew cask info iterm2-beta
Error: Cask 'iterm2-beta' definition is invalid: Bad header line: '{:v1=>"iterm2-beta"}' does not match file name
~ ☕️  brew cask search iterm2-beta
==> Exact match
iterm2-beta
~ ☕️
```

I've done `brew cleanup` , `brew doctor`, `brew cask doctor`, `brew cask cleanup` with no luck.

**Comment by vitorgalvao** [comment]
Either you haven’t `brew update` in a while (in which case, you must), or something is wrong with your tapping of this repo.

If updating doesn’t work, try untapping and tapping again. The issue is you’re trying to install an old version of the cask.
