### ISSUE TITLE
Should Pycharm Early Access be updated to the latest stable?

### ISSUE THREAD

**Issue by tjanson** [caskroom/homebrew-versions#1870]
[`pycharm-eap`](https://github.com/caskroom/homebrew-versions/blob/master/Casks/pycharm-eap.rb) currently sits at *5.1 Beta 2* (`145.256.43`). The latest release as part of the Early Access Program is *2016.1 RC2* (`145.259`).

However, *2016.1* has [since been released](http://blog.jetbrains.com/pycharm/2016/03/announcing-general-availability-of-pycharm-2016-1/) as the current stable version, and this version is linked on the [EAP page](https://confluence.jetbrains.com/display/PYH/JetBrains+PyCharm+Preview+(EAP)) – effectively suspending the Early Access program until a new preview is out.
I think the EAP cask should be updated to that stable version (temporarily coinciding with [the stable cask](https://github.com/caskroom/homebrew-cask/blob/master/Casks/pycharm.rb)). What do you think?

The same probably applies to other Jetbrains IDEA-based IDEs.

----

Edit: Actually, I just saw that the EAP versions prompt the user to update to *2016.1*, so I think that settles it. I’ll update the casks later when I get the time.

**Comment by vitorgalvao** [comment]
Agreed.
