### ISSUE TITLE
The sha256 for iTerm2-2_9_20160403-nightly.zip is wrong

### ISSUE THREAD

**Issue by ajkavanagh** [caskroom/homebrew-versions#1886]
The actual file, from the iterm2.com site is:

7aeb775f7e23b7ae07e0cac621cddf5bbce147fdadbbbad88e27ff96b7480d1c  iTerm2-2_9_20160403-nightly.zip

**Comment by vitorgalvao** [comment]
Mind submitting a PR?

**Comment by ajkavanagh** [comment]
Sure, if you'd like.
