### ISSUE TITLE
iterm2-beta app name is wrong

### ISSUE THREAD

**Issue by TiuTalk** [caskroom/homebrew-versions#2208]
The file created under `/Applications` is `/Applications/iTerm.app` but the _internal_ app name is `/Applications/iTerm.app/Contents/MacOS/iTerm2`.

I had to rename the package to `/Applications/iTerm2.app` to get it working again.

```shell
$ open /Applications/iTerm.app 
LSOpenURLsWithRole() failed with error -10810 for the file /Applications/iTerm.app.
```

**Comment by vitorgalvao** [comment]
Thank you for the report, but you need to report it upstream. We’re not changing the name of the app.
