### ISSUE TITLE
Sublimetext 3 dev needs updating

### ISSUE THREAD

**Issue by gianchub** [caskroom/homebrew-versions#2230]
Hello,

the dev version of sublimetext 3 is now at Build 3117.

Could you please update it?

Kind regards,
fab

**Comment by vitorgalvao** [comment]
That is no longer in this repo. It was moved to the main one.

**Comment by jawshooah** [comment]
@vitorgalvao He means `sublime-text-dev`, which is still here.

@gianchub Feel free to update the cask yourself and submit a PR.

**Comment by vitorgalvao** [comment]
Oh, right.

Closing again in favour of https://github.com/caskroom/homebrew-versions/pull/2232/.

**Comment by gianchub** [comment]
Thank you so much, I didn't know I could've done it myself. Kind regards, fab

**Comment by vitorgalvao** [comment]
https://github.com/caskroom/homebrew-cask/blob/master/CONTRIBUTING.md#updating-a-cask
