### ISSUE TITLE
Error whilst installing kicad-nightly

### ISSUE THREAD

**Issue by agatti** [caskroom/homebrew-versions#2308]
Hi there,

  when installing nightly KiCad builds I get an error from caskroom, although the application is installed correctly.  Shell messages follow:

```bash

agatti@tardigrade ~ $ brew update
Updated Homebrew from bf40dd6 to 8282744.
Updated 2 taps (caskroom/cask, homebrew/core).
==> Updated Formulae
s-search                                                                                                               tutum
agatti@tardigrade ~ $ brew cask zap kicad
==> Implied "brew cask uninstall kicad"
==> Removing App Suite: '/Applications/Kicad'
Warning: No zap stanza present for Cask 'kicad'
==> Removing all staged versions of Cask 'kicad'
agatti@tardigrade ~ $ brew cask zap kicad-nightly
==> Implied "brew cask uninstall kicad-nightly"
Warning: No zap stanza present for Cask 'kicad-nightly'
==> Removing all staged versions of Cask 'kicad-nightly'
agatti@tardigrade ~ $ brew cask install kicad-nightly
==> Downloading http://downloads.kicad-pcb.org/osx/nightly/kicad-r6775.20160506-034556.dmg
Already downloaded: /Users/agatti/Library/Caches/Homebrew/kicad-nightly-r6775.20160506-034556.dmg
==> Verifying checksum for Cask kicad-nightly
==> Moving App Suite 'Kicad' to '/Applications/Kicad'
Error: It seems the Generic artifact source is not there: '/usr/local/Caskroom/kicad-nightly/r6775.20160506-034556/kicad'
agatti@tardigrade ~ $ ls /Applications/Kicad
bitmap2component.app eeschema.app         help                 library              packages3d           pcbnew.app           share
demos                gerbview.app         kicad.app            modules              pcb_calculator.app   pl_editor.app        template
agatti@tardigrade ~ $ ls /usr/local/Caskroom/kicad-nightly
ls: /usr/local/Caskroom/kicad-nightly: No such file or directory
```

**Comment by vitorgalvao** [comment]
You must *always* follow the [reporting bugs](https://github.com/caskroom/homebrew-cask#reporting-bugs) guide.

When you opened this issue, the template in place even urged you to do so and gave you the relevant links.

If you will not spend the time to open an issue correctly, we will not spend the time to look at it. We spend hours every day to deal with non-trivial amounts of issues and pull requests and improve this project you use for free; the least you can do is spend a few minutes to make a correct report. Please respect our time.

This is pre-written text, and it is in no way said in anger. If I made a mistake in closing the issue, I ask that you correct me. I will reopen it and we can continue the discussion.

If, however, you have indeed not paid the due attention to the guide, go back and do. We will be waiting for your new properly formatted issue that will have most (if not all) the necessary details required for us to help you. With a little luck, you won’t even need to open a new issue (the instructions to report bugs include a lot of fixes for common problems).

Finally, if it was the guide itself that was unclear, make a new pull request with your suggestions on how to improve it.

Thank you. Have a good day.
