### ISSUE TITLE
Question: Idea CE

### ISSUE THREAD

**Issue by adamatti** [caskroom/homebrew-versions#2539]
This is now a defect, but just a question on Idea CE EAP (Early Access program).

Why it has two options for the EAP program? (intellij-idea-ce-eap.rb and intellij-idea-**next**-ce-eap.rb). In my POV, it should have only the latest one... if you install the first one it keep asking to update to the second one.

Thanks in advance, and sorry for the dumb question :-)

**Comment by metyl** [comment]
IntelliJ IDEA guys have up to 3 EAP channels for each IntelliJ version, please take a look at https://confluence.jetbrains.com/display/IDEADEV/EAP. 

So now current release is _2016.2.x_ and **next** is _2016.3_ and they are develop simultaneously. You can decide which version of EAP You would like to try for current released or for next release.

**Comment by vitorgalvao** [comment]
Closing as answered. Thank you @metyl.

**Comment by jawshooah** [comment]
@metyl it seems problematic that the IDE prompts the user to upgrade to the 2016.3 EAP even if they specifically downloaded the 2016.2 EAP. Do you know why that might be?

**Comment by metyl** [comment]
It depends which update channel You have configured in IDE Preferences.
BTW now we have good example for current version [2016.2](https://confluence.jetbrains.com/display/IDEADEV/IDEA+2016.2+EAP) in EAP we have 2016.2.4 RC and in the same time for next version [2016.3](https://confluence.jetbrains.com/display/IDEADEV/IDEA+2016.3+EAP) in EAP we have different build.

**Comment by jawshooah** [comment]
Got it, thanks!

**Comment by adamatti** [comment]
Thanks guys, it is clear now.
