### ISSUE TITLE
Update CONTRIBUTING.md

### ISSUE THREAD

**Issue by pat-s** [caskroom/homebrew-versions#2693]
Following the instructions for contributing: https://github.com/caskroom/homebrew-versions/blob/master/CONTRIBUTING.md

Line `cd $(brew --prefix)/Library/Taps/caskroom/homebrew-versions` did not work for me. Changing to `cd $(brew --prefix)/Homebrew/Library/Taps/caskroom/homebrew-versions/Casks` on my up to date brew framework worked. The path change was introduced lately in a brew core update?

Using the `cask-repair` script, the following approach was the way to contribute:

```
outdated_cask='<the-cask-i-want-to-update>'
github_user='<my-github-username>'
cd "$(brew --repository)/Homebrew/Library/Taps/caskroom/homebrew-versions/Casks"

cask-repair --pull origin --push $github_user $outdated_cask
```

**Comment by vitorgalvao** [comment]
[Fixed](https://github.com/caskroom/homebrew-versions/commit/55e316f6df3a5ce97a70319350da7a7b086f1a2f).
