### ISSUE TITLE
Outdated cask: emacs-nightly

### ISSUE THREAD

**Issue by Saklad5** [caskroom/homebrew-versions#2772]
Outdated cask: [`emacs-nightly`](https://github.com/caskroom/homebrew-versions/blob/master/Casks/emacs-nightly.rb).

Info:
+ version: `2016-10-06_01-43-38-6e6c08815347a78008211613c9ddfa0acd7f0ef8`.
+ appcast url: https://emacsformacosx.com/atom/daily.

**Comment by jonbash** [comment]
This seems to be outdated again.
