### ISSUE TITLE
Outdated cask: emacs-pretest

### ISSUE THREAD

**Issue by Saklad5** [caskroom/homebrew-versions#2773]
Outdated cask: [`emacs-pretest`](https://github.com/caskroom/homebrew-versions/blob/master/Casks/emacs-pretest.rb).

Info:
+ version: `25.1-rc1`.
+ appcast url: https://emacsformacosx.com/atom/pretest.

**Comment by jonbash** [comment]
This seems to be outdated again. Tried updating through provided script but ran into errors. Current version is 25.2-rc2.
