### ISSUE TITLE
parallels10 fails to install; Operation not permitted

### ISSUE THREAD

**Issue by akhomyakov** [caskroom/homebrew-versions#2851]
Experiencing this on a clean OS X system:

$ brew cask install caskroom/versions/parallels10
==> Downloading http://download.parallels.com/desktop/v10/10.3.0/ParallelsDesktop-10.3.0-29227.dmg
######################################################################## 100.0%
==> Verifying checksum for Cask parallels10
==> ditto: /usr/local/Caskroom/parallels10/10.3.0-29227/Parallels Desktop.app/Contents/MacOS/Shared Application Group B
Error: Command failed to execute!

==> Failed command:
/usr/bin/ditto --bom /var/folders/59/7fly7_r97mjf8s9rp3gzjs2hn4xtgr/T/20161106-16247-1marsfn.bom -- /private/tmp/dmg.Q69gY6 #<Pathname:/usr/local/Caskroom/parallels10/10.3.0-29227>

==> Standard Output of failed command:

==> Standard Error of failed command:
ditto: /usr/local/Caskroom/parallels10/10.3.0-29227/Parallels Desktop.app/Contents/MacOS/Shared Application Group Bridge.app/Contents/PkgInfo: Operation not permitted

==> Exit status of failed command:
#<Process::Status: pid 16409 exit 1>

**Comment by vitorgalvao** [comment]
From the [issue template](https://github.com/caskroom/homebrew-cask/blob/master/.github/ISSUE_TEMPLATE.md) that shows when opening a new issue:

> Before opening your issue **you must check our instructions** for [reporting bugs](https://github.com/caskroom/homebrew-cask#reporting-bugs) (…) [it] has several links to help diagnose and fix common issues.

> (…)

> **if it is apparent you ignored the instructions for reporting issues, we may close the issue without review**.

That seems to be the case, which is why I closed this issue. We worked hard  on those guides to keep things running smoothly, so I ask that you go back and follow them. It is OK to open a new issue for that.

If I was wrong in closing this issue, please do reply stating why! Closing an issue does not mean the conversation is over.

I understand sometimes we’re tired and don’t want to sift through a guide to make what we feel is a simple bug report. But when each user ignores the guides to save a few minutes, maintainers lose hours and get fatigued. I ask you take that into consideration.

Thank you for understanding.

**Comment by homa2001** [comment]
I did review the reporting bugs, tried reinstalling brew as noted in one of the steps and checked permissions as noted in another step. None of the options seem to describe my case above. I'm not even sure what the command that is failing trying to do that it's not permitted. Ditto seems to be used for copying directory structures, but I don't fully understand where and what it's trying to copy in this case.

**Comment by vitorgalvao** [comment]
What we need is for you to follow [this template](https://github.com/caskroom/homebrew-cask/issues/new?title=Bug%20report%3A%20%5Bsummarise%20the%20issue%20here%5D&body=Remember%20to%20follow%20the%20%5Bpre%20bug%20report%5D%28https%3A%2F%2Fgithub.com%2Fcaskroom%2Fhomebrew-cask%2Fblob%2Fmaster%2Fdoc%2Freporting_bugs%2Fpre_bug_report.md%29%20guide%20beforehand.%20Failure%20to%20do%20so%20might%20get%20your%20issue%20closed.%0A%0A%23%23%23%23%20Description%20of%20issue%0A%0A%5Binsert%20a%20detailed%20description%20of%20your%20issue%20here%5D%0A%0A%3Cdetails%3E%3Csummary%3EOutput%20of%20%60brew%20cask%20%3Ccommand%3E%20--verbose%60%3C%2Fsummary%3E%0A%0A%60%60%60%0A%5Bpaste%20output%20here%5D%0A%60%60%60%0A%3C%2Fdetails%3E%0A%0A%3Cdetails%3E%3Csummary%3EOutput%20of%20%60brew%20doctor%60%3C%2Fsummary%3E%0A%0A%60%60%60%0A%5Bpaste%20output%20here%5D%0A%60%60%60%0A%3C%2Fdetails%3E%0A%0A%3Cdetails%3E%3Csummary%3EOutput%20of%20%60brew%20cask%20doctor%60%3C%2Fsummary%3E%0A%0A%60%60%60%0A%5Bpaste%20output%20here%5D%0A%60%60%60%0A%3C%2Fdetails%3E%0A)

**Comment by homa2001** [comment]
Sorry, I must have missed that link somehow. Here it is:

Remember to follow the [pre bug report](https://github.com/caskroom/homebrew-cask/blob/master/doc/reporting_bugs/pre_bug_report.md) guide beforehand. Failure to do so might get your issue closed.

#### Description of issue

Trying to install parallels10 on Mac OS Sierra 10.12.1. Clean build.

<details><summary>Output of `brew cask <command> --verbose`</summary>

```
$> brew cask install caskroom/versions/parallels10 --verbose
==> Downloading http://download.parallels.com/desktop/v10/10.3.0/ParallelsDesktop-10.3.0-29227.dmg
Already downloaded: /Users/akhomyakov/Library/Caches/Homebrew/Cask/parallels10--10.3.0-29227.dmg
==> Verifying checksum for Cask parallels10
==> ditto: /usr/local/Caskroom/parallels10/10.3.0-29227/Parallels Desktop.app/Contents/MacOS/Shared Application Group Bridge.app/Contents/PkgInfo: Operation not permitted
Error: Command failed to execute!

==> Failed command:
/usr/bin/ditto --bom /var/folders/59/7fly7_r97mjf8s9rp3gzjs2hn4xtgr/T/20161107-1675-1lqudmn.bom -- /private/tmp/dmg.61CslA #<Pathname:/usr/local/Caskroom/parallels10/10.3.0-29227>

==> Standard Output of failed command:


==> Standard Error of failed command:
ditto: /usr/local/Caskroom/parallels10/10.3.0-29227/Parallels Desktop.app/Contents/MacOS/Shared Application Group Bridge.app/Contents/PkgInfo: Operation not permitted


==> Exit status of failed command:
#<Process::Status: pid 1817 exit 1>
Error: Kernel.exit
akhomyakov@013158:~

```
</details>

<details><summary>Output of `brew doctor`</summary>

```
$> brew doctor
Please note that these warnings are just used to help the Homebrew maintainers
with debugging if you file an issue. If everything you use Homebrew for is
working fine: please don't worry and just ignore them. Thanks!

Warning: Homebrew's sbin was not found in your PATH but you have installed
formulae that put executables in /usr/local/sbin.
Consider setting the PATH for example like so
  echo 'export PATH="/usr/local/sbin:$PATH"' >> ~/.bash_profile

```
</details>

<details><summary>Output of `brew cask doctor`</summary>

```
$> brew cask doctor
==> macOS Release:
10.12.1
==> Hardware Architecture:
intel-64
==> Ruby Version:
2.0.0-p648
==> Ruby Path:
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/bin/ruby
==> Homebrew Version:
Homebrew >1.0.0 (no git repository)
Homebrew/homebrew-core (git revision 3a20; last commit 2016-11-06)
==> Homebrew Executable Path:
/usr/local/bin/brew
==> Homebrew Cellar Path:
/usr/local/Cellar
==> Homebrew Repository Path:
/usr/local/Homebrew
==> Homebrew Origin:
https://github.com/Homebrew/brew
==> Homebrew-Cask Version:
Homebrew-Cask >1.0.0 (no git repository)
caskroom/homebrew-cask (git revision fe47; last commit 2016-11-06)
==> Homebrew-Cask Install Location:
<NONE>
==> Homebrew-Cask Staging Location:
/usr/local/Caskroom
==> Homebrew-Cask Cached Downloads:
/Users/akhomyakov/Library/Caches/Homebrew/Cask
7 files, 480M (warning: run "brew cask cleanup")
==> Homebrew-Cask Default Tap Path:
/usr/local/Homebrew/Library/Taps/caskroom/homebrew-cask
==> Homebrew-Cask Alternate Cask Taps:
/usr/local/Homebrew/Library/Taps/caskroom/homebrew-versions
==> Homebrew-Cask Default Tap Cask Count:
3432
==> Contents of $LOAD_PATH:
/usr/local/Homebrew/Library/Homebrew/cask/lib
/usr/local/Homebrew/Library/Homebrew
/Library/Ruby/Site/2.0.0
/Library/Ruby/Site/2.0.0/x86_64-darwin16
/Library/Ruby/Site/2.0.0/universal-darwin16
/Library/Ruby/Site
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/vendor_ruby/2.0.0
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/vendor_ruby/2.0.0/x86_64-darwin16
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/vendor_ruby/2.0.0/universal-darwin16
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/vendor_ruby
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/x86_64-darwin16
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/universal-darwin16
==> Contents of $RUBYLIB Environment Variable:
<NONE>
==> Contents of $RUBYOPT Environment Variable:
<NONE>
==> Contents of $RUBYPATH Environment Variable:
<NONE>
==> Contents of $RBENV_VERSION Environment Variable:
<NONE>
==> Contents of $CHRUBY_VERSION Environment Variable:
<NONE>
==> Contents of $GEM_HOME Environment Variable:
<NONE>
==> Contents of $GEM_PATH Environment Variable:
<NONE>
==> Contents of $BUNDLE_PATH Environment Variable:
<NONE>
==> Contents of $PATH Environment Variable:
PATH="/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/Homebrew/Library/Taps/buo/homebrew-cask-upgrade/cmd:/usr/local/Homebrew/Library/Homebrew/cask/cmd:/usr/local/Homebrew/Library/Homebrew/shims/scm"
==> Contents of $SHELL Environment Variable:
SHELL="/bin/bash"
==> Contents of Locale Environment Variables:
LANG="en_US.UTF-8"
==> Running As Privileged User:
No

```
</details>

**Comment by vitorgalvao** [comment]
Seems like your installation might be outdated.

Try `brew update --force` and try again. If that does not work, try `cd "$(brew --repo)" && git fetch && git reset --hard origin/master && brew update` or check out https://github.com/Homebrew/brew/blob/master/docs/Troubleshooting.md#troubleshooting.

**Comment by homa2001** [comment]
This is literally the first thing I tried, since it's your troubleshooting
guide to try before opening an issue.
What makes you think that I have an outdated install? It would be odd to
end up with an outdated install considering this is a freshly built OS, so
I just installed brew.


--Andrey

**Comment by vitorgalvao** [comment]
> What makes you think that I have an outdated install?

`doctor`:

> ==> Homebrew Version:
> Homebrew >1.0.0 (no git repository)

The commands I gave are not in the guide, they are to fix a recent issue with HB. That message is not normal.

**Comment by homa2001** [comment]
Unfortunately, no dice :(

$> brew update --force
Updated 4 taps (buo/cask-upgrade, caskroom/cask, caskroom/versions, homebrew/core).
==> Updated Formulae
consul-backinator                                            typesafe-activator
$> brew doctor
Please note that these warnings are just used to help the Homebrew maintainers
with debugging if you file an issue. If everything you use Homebrew for is
working fine: please don't worry and just ignore them. Thanks!

Warning: Homebrew's sbin was not found in your PATH but you have installed
formulae that put executables in /usr/local/sbin.
Consider setting the PATH for example like so
  echo 'export PATH="/usr/local/sbin:$PATH"' >> ~/.bash_profile
$> brew cask doctor
==> macOS Release:
10.12.1
==> Hardware Architecture:
intel-64
==> Ruby Version:
2.0.0-p648
==> Ruby Path:
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/bin/ruby
==> Homebrew Version:
Homebrew 1.1.0
Homebrew/homebrew-core (git revision 0fb6; last commit 2016-11-10)
==> Homebrew Executable Path:
/usr/local/bin/brew
==> Homebrew Cellar Path:
/usr/local/Cellar
==> Homebrew Repository Path:
/usr/local/Homebrew
==> Homebrew Origin:
https://github.com/Homebrew/brew
==> Homebrew-Cask Version:
Homebrew-Cask 1.1.0
caskroom/homebrew-cask (git revision bebd9; last commit 2016-11-10)
==> Homebrew-Cask Install Location:
<NONE>
==> Homebrew-Cask Staging Location:
/usr/local/Caskroom
==> Homebrew-Cask Cached Downloads:
/Users/akhomyakov/Library/Caches/Homebrew/Cask
10 files, 760.7M (warning: run "brew cask cleanup")
==> Homebrew-Cask Default Tap Path:
/usr/local/Homebrew/Library/Taps/caskroom/homebrew-cask
==> Homebrew-Cask Alternate Cask Taps:
/usr/local/Homebrew/Library/Taps/caskroom/homebrew-versions
==> Homebrew-Cask Default Tap Cask Count:
3416
==> Contents of $LOAD_PATH:
/usr/local/Homebrew/Library/Homebrew/cask/lib
/usr/local/Homebrew/Library/Homebrew
/Library/Ruby/Site/2.0.0
/Library/Ruby/Site/2.0.0/x86_64-darwin16
/Library/Ruby/Site/2.0.0/universal-darwin16
/Library/Ruby/Site
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/vendor_ruby/2.0.0
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/vendor_ruby/2.0.0/x86_64-darwin16
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/vendor_ruby/2.0.0/universal-darwin16
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/vendor_ruby
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/x86_64-darwin16
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/universal-darwin16
==> Contents of $RUBYLIB Environment Variable:
<NONE>
==> Contents of $RUBYOPT Environment Variable:
<NONE>
==> Contents of $RUBYPATH Environment Variable:
<NONE>
==> Contents of $RBENV_VERSION Environment Variable:
<NONE>
==> Contents of $CHRUBY_VERSION Environment Variable:
<NONE>
==> Contents of $GEM_HOME Environment Variable:
<NONE>
==> Contents of $GEM_PATH Environment Variable:
<NONE>
==> Contents of $BUNDLE_PATH Environment Variable:
<NONE>
==> Contents of $PATH Environment Variable:
PATH="/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/Homebrew/Library/Taps/buo/homebrew-cask-upgrade/cmd:/usr/local/Homebrew/Library/Homebrew/cask/cmd:/usr/local/Homebrew/Library/Homebrew/shims/scm"
==> Contents of $SHELL Environment Variable:
SHELL="/bin/bash"
==> Contents of Locale Environment Variables:
LANG="en_US.UTF-8"
==> Running As Privileged User:
No
$> brew cask install caskroom/versions/parallels10 --verbose
==> Downloading http://download.parallels.com/desktop/v10/10.3.0/ParallelsDesktop-10.3.0-29227.dmg
Already downloaded: /Users/akhomyakov/Library/Caches/Homebrew/Cask/parallels10--10.3.0-29227.dmg
==> Verifying checksum for Cask parallels10
==> ditto: /usr/local/Caskroom/parallels10/10.3.0-29227/Parallels Desktop.app/Contents/MacOS/Shared Application Group Bridge.app/Contents/PkgInfo: Operation not permitted
Error: Command failed to execute!

==> Failed command:
/usr/bin/ditto --bom /var/folders/59/7fly7_r97mjf8s9rp3gzjs2hn4xtgr/T/20161110-29210-18uktz3.bom -- /private/tmp/dmg.aHT4sM #<Pathname:/usr/local/Caskroom/parallels10/10.3.0-29227>

==> Standard Output of failed command:


==> Standard Error of failed command:
ditto: /usr/local/Caskroom/parallels10/10.3.0-29227/Parallels Desktop.app/Contents/MacOS/Shared Application Group Bridge.app/Contents/PkgInfo: Operation not permitted


==> Exit status of failed command:
#<Process::Status: pid 29352 exit 1>
Error: Kernel.exit
$> cd "$(brew --repo)" && git fetch && git reset --hard origin/master && brew update
HEAD is now at c2815fb Merge pull request #1381 from adzenith/patch-1
Already up-to-date.
$> brew cask install caskroom/versions/parallels10 --verbose
==> Downloading http://download.parallels.com/desktop/v10/10.3.0/ParallelsDesktop-10.3.0-29227.dmg
Already downloaded: /Users/akhomyakov/Library/Caches/Homebrew/Cask/parallels10--10.3.0-29227.dmg
==> Verifying checksum for Cask parallels10
==> ditto: /usr/local/Caskroom/parallels10/10.3.0-29227/Parallels Desktop.app/Contents/MacOS/Shared Application Group Bridge.app/Contents/PkgInfo: Operation not permitted
Error: Command failed to execute!

==> Failed command:
/usr/bin/ditto --bom /var/folders/59/7fly7_r97mjf8s9rp3gzjs2hn4xtgr/T/20161110-29760-1wwvz80.bom -- /private/tmp/dmg.IJSM9x #<Pathname:/usr/local/Caskroom/parallels10/10.3.0-29227>

==> Standard Output of failed command:


==> Standard Error of failed command:
ditto: /usr/local/Caskroom/parallels10/10.3.0-29227/Parallels Desktop.app/Contents/MacOS/Shared Application Group Bridge.app/Contents/PkgInfo: Operation not permitted


==> Exit status of failed command:
#<Process::Status: pid 29902 exit 1>
Error: Kernel.exit
$>

**Comment by vitorgalvao** [comment]
I currently don’t have a VM to test this on (and won’t have one until Veertu can virtualise macOS).

**Comment by homa2001** [comment]
Can I help in any way?

**Comment by vitorgalvao** [comment]
You can try installing this (and other versions) on a fresh virtual machine and see if you get the same errors. You can also try to run the failed commands themselves to see if and how they fail.

**Comment by fanquake** [comment]
@homa2001 Do you have any more feedback about this issue?

**Comment by miccal** [comment]
@akhomyakov do you have any more feedback about this issue?

**Comment by akhomyakov** [comment]
Sorry, folks, I never got around to testing this. Probably just close it
out as it is probably of low value to everyone to spend on this.


--Andrey

**Comment by condemil** [comment]
I have the same issue and reported it here: https://github.com/Homebrew/homebrew-versions/issues/1449
