### ISSUE TITLE
Migrations to main repo

### ISSUE THREAD

**Issue by miccal** [caskroom/homebrew-versions#3219]
With https://github.com/caskroom/homebrew-cask/pull/29356 requiring the moving of editions to the main repo, I have compiled the following list of Casks that I _think_ should be moved:

- [x] [ableton-live-lite.rb](../blob/master/Casks/ableton-live-lite.rb)
- [x] [ableton-live-standard.rb](../blob/master/Casks/ableton-live-standard.rb)
- [x] [ableton-live-suite.rb](../blob/master/Casks/ableton-live-suite.rb)
- [ ] [adobe-cs6-design-standard.rb](../blob/master/Casks/adobe-cs6-design-standard.rb)
- [ ] [adobe-cs6-design-web-premium.rb](../blob/master/Casks/adobe-cs6-design-web-premium.rb)
- [ ] [adobe-cs6-master-collection.rb](../blob/master/Casks/adobe-cs6-master-collection.rb)
- [ ] [adobe-cs6-production-premium.rb](../blob/master/Casks/adobe-cs6-production-premium.rb)
- [ ] [adobe-digital-editions2.rb](../blob/master/Casks/adobe-digital-editions2.rb)
- [ ] [adobe-photoshop-cs6.rb](../blob/master/Casks/adobe-photoshop-cs6.rb)
- [ ] [adobe-photoshop-lightroom441.rb](../blob/master/Casks/adobe-photoshop-lightroom441.rb)
- [ ] [adobe-photoshop-lightroom571.rb](../blob/master/Casks/adobe-photoshop-lightroom571.rb)
- [ ] [adobe-photoshop-lightroom600.rb](../blob/master/Casks/adobe-photoshop-lightroom600.rb)
- [x] [air-video-server.rb](../blob/master/Casks/air-video-server.rb)
- [ ] [alfred2.rb](../blob/master/Casks/alfred2.rb)
- [ ] [amadeus-pro1.rb](../blob/master/Casks/amadeus-pro1.rb)
- [ ] [anaconda2.rb](../blob/master/Casks/anaconda2.rb)
- [ ] [android-studio-canary.rb](../blob/master/Casks/android-studio-canary.rb)
- [x] [beaker-electron.rb](../blob/master/Casks/beaker-electron.rb)
- [ ] [charles-applejava.rb](../blob/master/Casks/charles-applejava.rb)
- [ ] [cocoapods0.rb](../blob/master/Casks/cocoapods0.rb)
- [ ] [dash2.rb](../blob/master/Casks/dash2.rb)
- [x] [dbeaver-community.rb](../blob/master/Casks/dbeaver-community.rb)
- [x] [dmm-player-for-chrome.rb](../blob/master/Casks/dmm-player-for-chrome.rb)
- [ ] [dosbox-svn.rb](../blob/master/Casks/dosbox-svn.rb)
- [ ] [earlybird.rb](../blob/master/Casks/earlybird.rb)
- [ ] [firefox-esr.rb](../blob/master/Casks/firefox-esr.rb)
- [x] [flash-player-debugger-npapi.rb](../blob/master/Casks/flash-player-debugger-npapi.rb)
- [x] [flash-player-debugger-ppapi.rb](../blob/master/Casks/flash-player-debugger-ppapi.rb)
- [x] [flash-player-debugger.rb](../blob/master/Casks/flash-player-debugger.rb)
- [ ] [gemini-classic.rb](../blob/master/Casks/gemini-classic.rb)
- [ ] [google-chrome-canary.rb](../blob/master/Casks/google-chrome-canary.rb)
- [x] [intellij-idea-ce.rb](../blob/master/Casks/intellij-idea-ce.rb)
- [ ] [iterm2-legacy.rb](../blob/master/Casks/iterm2-legacy.rb)
- [ ] [java6.rb](../blob/master/Casks/java6.rb)
- [ ] [java7.rb](../blob/master/Casks/java7.rb)
- [ ] [josm-latest.rb](../blob/master/Casks/josm-latest.rb)
- [ ] [keyboard-maestro6.rb](../blob/master/Casks/keyboard-maestro6.rb)
- [ ] [lingon-x2.rb](../blob/master/Casks/lingon-x2.rb)
- [ ] [macvim-kaoriya.rb](../blob/master/Casks/macvim-kaoriya.rb)
- [x] [macx-dvd-ripper-pro.rb](../blob/master/Casks/macx-dvd-ripper-pro.rb)
- [x] [maltego-chlorine-ce.rb](../blob/master/Casks/maltego-chlorine-ce.rb)
- [ ] [microsoft-office-2011.rb](../blob/master/Casks/microsoft-office-2011.rb)
- [x] [multimarkdown-composer-pro.rb](../blob/master/Casks/multimarkdown-composer-pro.rb)
- [ ] [mumble.rb](../blob/master/Casks/mumble.rb)
- [ ] [omnigraffle5.rb](../blob/master/Casks/omnigraffle5.rb)
- [ ] [omnigraffle6.rb](../blob/master/Casks/omnigraffle6.rb)
- [x] [opera-neon.rb](../blob/master/Casks/opera-neon.rb)
- [ ] [palemoon.rb](../blob/master/Casks/palemoon.rb)
- [ ] [parallels-desktop10.rb](../blob/master/Casks/parallels-desktop10.rb)
- [ ] [parallels-desktop11.rb](../blob/master/Casks/parallels-desktop11.rb)
- [x] [pdfpenpro.rb](../blob/master/Casks/pdfpenpro.rb)
- [ ] [pgadmin3.rb](../blob/master/Casks/pgadmin3.rb)
- [ ] [porting-kit-legacy.rb](../blob/master/Casks/porting-kit-legacy.rb)
- [ ] [processing2.rb](../blob/master/Casks/processing2.rb)
- [x] [pycharm-ce.rb](../blob/master/Casks/pycharm-ce.rb)
- [x] [pycharm-edu.rb](../blob/master/Casks/pycharm-edu.rb)
- [ ] [quickbooks-desktop2014.rb](../blob/master/Casks/quickbooks-desktop2014.rb)
- [ ] [quickbooks-desktop2015.rb](../blob/master/Casks/quickbooks-desktop2015.rb)
- [ ] [rhinoceroswip.rb](../blob/master/Casks/rhinoceroswip.rb)
- [ ] [safari-technology-preview.rb](../blob/master/Casks/safari-technology-preview.rb)
- [ ] [scansnap-manager-s1300.rb](../blob/master/Casks/scansnap-manager-s1300.rb)
- [ ] [scansnap-manager-s1500.rb](../blob/master/Casks/scansnap-manager-s1500.rb)
- [ ] [scansnap-manager-s300m-s500m-s510m-fi-5110eoxm-legacy.rb](../blob/master/Casks/scansnap-manager-s300m-s500m-s510m-fi-5110eoxm-legacy.rb)
- [ ] [scansnap-manager-s300m-s510m.rb](../blob/master/Casks/scansnap-manager-s300m-s510m.rb)
- [ ] [scansnap-manager-sv600.rb](../blob/master/Casks/scansnap-manager-sv600.rb)
- [ ] [screenflow5.rb](../blob/master/Casks/screenflow5.rb)
- [ ] [shimo3.rb](../blob/master/Casks/shimo3.rb)
- [x] [sketchup-pro.rb](../blob/master/Casks/sketchup-pro.rb)
- [ ] [snagit3.rb](../blob/master/Casks/snagit3.rb)
- [ ] [spyder-py2.rb](../blob/master/Casks/spyder-py2.rb)
- [ ] [sublime-text2.rb](../blob/master/Casks/sublime-text2.rb)
- [ ] [totals2.rb](../blob/master/Casks/totals2.rb)
- [ ] ~~[umsatz-mini.rb](../blob/master/Casks/umsatz-mini.rb)~~ (removed)
- [ ] ~~[umsatz-pro.rb](../blob/master/Casks/umsatz-pro.rb)~~ (removed)
- [ ] [unison240.rb](../blob/master/Casks/unison240.rb)
- [ ] [unity523.rb](../blob/master/Casks/unity523.rb)
- [x] [visual-paradigm-ce.rb](../blob/master/Casks/visual-paradigm-ce.rb)
- [ ] [vmware-fusion6.rb](../blob/master/Casks/vmware-fusion6.rb)
- [ ] [vmware-fusion7.rb](../blob/master/Casks/vmware-fusion7.rb)
- [ ] [vox0.rb](../blob/master/Casks/vox0.rb)
- [ ] [zulu7.rb](../blob/master/Casks/zulu7.rb)

As a first step, can @caskroom/maintainers please review the Casks in this list and tick the ones you agree with, and add any Casks I may have missed by mistake.

**Comment by adidalal** [comment]
Scansnap casks feel like drivers to me

**Comment by vitorgalvao** [comment]
> Scansnap casks feel like drivers to me

I was also going to comment that.

**Comment by vitorgalvao** [comment]
@miccal You’re mixing some versions with editions, things like `vmware-fusion6`, `java6`, and `screenflow5` are old versions, not different editions. They belong in this repo.

**Comment by vitorgalvao** [comment]
`canary` versions also belong in this repo.

**Comment by vitorgalvao** [comment]
`earlybird` belongs here as well.

What are the casks that you have checked on the list? What do they represent?

**Comment by reitermarkus** [comment]
@vitorgalvao, I was the one who checked them. I missed that `canary` versions should stay in `versions`, I unchecked them again.

**Comment by vitorgalvao** [comment]
@reitermarkus Ah, you’re checking the ones you agree with. That’s fine, I like the system (better than directly editing the list).

**Comment by miccal** [comment]
@vitorgalvao I am not checking anything at this stage.

**Comment by miccal** [comment]
> @miccal You’re mixing some versions with editions, things like vmware-fusion6, java6, and screenflow5 are old versions, not different editions. They belong in this repo. canary versions and earlybird belong here as well.

I was unsure about these, thanks for clarifying.

**Comment by vitorgalvao** [comment]
Edited the list to link to the casks.

**Comment by miccal** [comment]
Note that I basically generated the list by removing Casks with `beta`, `dev`, `nightly`, `eap`, `alpha`, `daily` and `test`.

**Comment by vitorgalvao** [comment]
> Note that I basically generated the list by removing Casks with `beta`, `dev`, `nightly`, `eap`, `alpha`, `daily` and `test`.

That’s good. It means we’re looking at everything but the less obvious ones. Thank you.

**Comment by miccal** [comment]
> Edited the list to link to the casks.

How the hell did you do that so fast?

**Comment by reitermarkus** [comment]
`dupeguru-me` and `dupeguru-pe`, which I had crossed out, are missing now.

**Comment by vitorgalvao** [comment]
> `dupeguru-me` and `dupeguru-pe`, which I had crossed out, are missing now.

That was me (https://github.com/caskroom/homebrew-versions/pull/3220 and https://github.com/caskroom/homebrew-versions/pull/3221).

**Comment by reitermarkus** [comment]
@vitorgalvao, great, thanks. 👍

**Comment by reitermarkus** [comment]
Almost the same goes for `umsatz-mini` and `umsatz-pro`. `umsatz` is a paid upgrade (version 2017), so these should also be removed or renamed to `umsatz-mini-2015` and `umsatz-pro-2015`.

**Comment by vitorgalvao** [comment]
> > Edited the list to link to the casks.
>
> How the hell did you do that so fast?

Vim macro. Though it could also be done with a simple regex: copy list, `pbpaste | sed -E 's|(- \[.\]) (.*)|\1 [\2](../blob/master/Casks/\2)|' | pbcopy`, paste.

**Comment by vitorgalvao** [comment]
> so these should also be removed or renamed to `umsatz-mini-2015` and `umsatz-pro-2015`

In this repo, I always vote for removal. If someone really misses old versions, they’ll be resubmitted.

**Comment by vitorgalvao** [comment]
Finished going through the list. With the current checks, it looks correct to me.

**Comment by miccal** [comment]
Thanks to everyone for the prompt reply - migrations are now done: see https://github.com/caskroom/homebrew-cask/pull/29552 and https://github.com/caskroom/homebrew-versions/pull/3231.
