### ISSUE TITLE
Migrations to caskroom/drivers

### ISSUE THREAD

**Issue by miccal** [caskroom/homebrew-versions#3232]
With https://github.com/caskroom/homebrew-cask/pull/29356 requiring the moving of drivers to their own repo, I have compiled the following list of Casks that I _think_ should be moved:

- [X] [scansnap-manager-s1300.rb](../blob/master/Casks/scansnap-manager-s1300.rb)
- [X] [scansnap-manager-s1500.rb](../blob/master/Casks/scansnap-manager-s1500.rb)
- [X] [scansnap-manager-s300m-s500m-s510m-fi-5110eoxm-legacy.rb](../blob/master/Casks/scansnap-manager-s300m-s500m-s510m-fi-5110eoxm-legacy.rb)
- [X] [scansnap-manager-s300m-s510m.rb](../blob/master/Casks/scansnap-manager-s300m-s510m.rb)
- [X] [scansnap-manager-sv600.rb](../blob/master/Casks/scansnap-manager-sv600.rb)
- [X] [unifi-controller-beta.rb](../blob/master/Casks/unifi-controller-beta.rb)

As a first step, can @caskroom/maintainers please review the Casks in this list, and add any Casks I may have missed by mistake.

**Comment by vitorgalvao** [comment]
Skimmed all casks. Looks correct.

**Comment by miccal** [comment]
@vitorgalvao do you have any clever suggestions for finding drivers in the main repo?

**Comment by vitorgalvao** [comment]
> @vitorgalvao do you have any clever suggestions for finding drivers in the main repo?

Nope. We’ll have to search them all individually, unfortunately. Maybe best to do individual PRs for each we find initially (the most obvious ones), and then we can do a more general pass.

Probably will work better than trying to do them all at once.

**Comment by claui** [comment]
[Boxcryptor](https://www.boxcryptor.com/en/download) claims to create a »virtual drive« in the Finder.

> After installation, Boxcryptor creates a virtual drive located under your home directory. Start Boxcryptor, sign in and you will see that Boxcryptor already added all your cloud storage providers automatically.

As this is not based on any real device (as in: hardware) I assume we’re not willing to count this as a driver though.

**Comment by claui** [comment]
`cura-beta` appears to have a set of [built-in printer drivers](https://ultimaker.com/en/resources/20460-manage-printers) accessible from within the app. However, those appear to be inside the `.app` so I figure we want to ignore this one, too?

**Comment by vitorgalvao** [comment]
@claui Yes to both of those. The idea of a driver is “this software is useless unless you have the accompanying hardware”.

**Comment by claui** [comment]
`unifi-controller-beta` looks like a borderline app-driver chimera for me, too.

Its [stanza’ed homepage](https://community.ubnt.com/t5/UniFi-Wireless-Beta/bd-p/UniFi_Beta) hides behind a registration wall but it has some [release notes](https://community.ubnt.com/t5/UniFi-Updates-Blog/UniFi-5-4-9-Stable-has-been-released/ba-p/1800599).

**Comment by vitorgalvao** [comment]
@claui I was unsure about that cask. I see it does indeed have some hardware, so it should count as a driver.

**Comment by claui** [comment]
Lastly, we have `arduino-nightly`. It is an IDE which – out of the box – drives a lot of different hardware interfaces for all those tinker boards. Ultimately, it does have some (limited) use even without the hardware. @vitorgalvao As per the definition you stated, this one would be a “nope”.

**Comment by claui** [comment]
That’s all I could find!

**Comment by vitorgalvao** [comment]
@claui Missed the arduino one in this repo. That one is a tough one as well. I guess it might be a non-driver as well.

**Comment by vitorgalvao** [comment]
Added `unifi-controller-beta` to the list.

**Comment by adidalal** [comment]
unifi controller should definitely be a driver - needs unifi (wireless) hardware to work

**Comment by miccal** [comment]
Thanks to everyone for the prompt reply, migrations are now done: see https://github.com/caskroom/homebrew-versions/pull/3236 and https://github.com/caskroom/homebrew-drivers/pull/1.
