### ISSUE TITLE
Should we put latest stable version in -dev cask?

### ISSUE THREAD

**Issue by yurikoles** [caskroom/homebrew-versions#3554]
For example the latest version of `telegram-destkop-dev` is `1.0.25.alpha`, stable version is higher, `1.0.27`. Should we also put the latest stable version in `telegram-desktop-dev`?

**Comment by neutric** [comment]
It has been done before in at least one of the JetBrains casks, if I remember correctly, so I'd say go ahead and submit the PR.

**Comment by yurikoles** [comment]
@neutric I want to hear official statement on this and to document it somewhere.

**Comment by vitorgalvao** [comment]
@yurikoles There’s no rule. Open the issue on the main repo instead, so we can discuss it properly.

**Comment by yurikoles** [comment]
@vitorgalvao I think this is correct repo for this question, since all pre-release cask are here.

**Comment by vitorgalvao** [comment]
@yurikoles This is not the correct repo, because this policy hasn’t been decided, and as such needs to be discussed. Discussions happen on the repo with the most visibility.
