### ISSUE TITLE
Rename Google Chrome Dev to avoid conflict with Google Chrome

### ISSUE THREAD

**Issue by OliverJAsh** [caskroom/homebrew-versions#3621]
`google-chrome` and `google-chrome-dev` casks both share the same app name, `Google Chrome.app`, which means they conflict.

Can we change `google-chrome-dev`’s app name to include a " Dev" suffix?

**Comment by vitorgalvao** [comment]
Nope. We [sometimes make exceptions but this isn’t one of those cases](https://github.com/caskroom/homebrew-cask/blob/master/doc/cask_language_reference/stanzas/app.md#target-should-only-be-used-in-select-cases). There’s a reason Google named their apps that way (Canary is different, after all) and we try not to impose names on users.

**Comment by OliverJAsh** [comment]
> There’s a reason Google named their apps that way (Canary is different, after all)

Google Chrome Dev is also different from Google Chrome.

I want to have both installed on my system. What should I do?

**Comment by vitorgalvao** [comment]
> I want to have both installed on my system. What should I do?

The same thing you’d do if Homebrew-Cask did not exist. Rename it after installing.
