### ISSUE TITLE
Source not there and cannot find it: phpstorm-eap

### ISSUE THREAD

**Issue by geekish** [caskroom/homebrew-versions#3630]
I am having trouble 'updating' [phpstorm-eap](https://github.com/caskroom/homebrew-versions/blob/master/Casks/phpstorm-eap.rb). I have, in the past, successfully updated using `brew cask install --force phpstorm-eap`. Command output:

```
brew cask install --force phpstorm-eap
==> Downloading https://download.jetbrains.com/webide/PhpStorm-EAP-171.4073.14.dmg
Already downloaded: /Users/hannahwarmbier/Library/Caches/Homebrew/Cask/phpstorm-eap--2017.1,171.4073.14.dmg
==> Verifying checksum for Cask phpstorm-eap
Error: It seems the App source '/usr/local/Caskroom/phpstorm-eap/2017.1,171.4073.14/PhpStorm 2017.1 EAP.app' is not there.
Error: nothing to install
```

The .app file in the .dmg is named "PhpStorm 2017.1.1 EAP.app", but it appears cask is looking for "PhpStorm 2017.1 EAP.app".

**Comment by vitorgalvao** [comment]
Thank you for actually following the reporting bugs guide and using the template. The amount of people that completely ignore it (despite all the notes) is staggering.

It looks like this is already at `2017.1.2` and build `2017.1.2,171.4249.3`, but the same download URL is not working for me (I’m only finding the non-EAP). Good thing we have many Jetbrains users as regular contributors.

@leipert You made the most recent changes *en masse*. Mind taking a look?

**Comment by gobinathm** [comment]
Based on my research last week the EAP download is not available any more as the final release came out. Turns out the EAP might be available in few months for 2018

**Comment by miccal** [comment]
Ping @leipert for any insight.

**Comment by leipert** [comment]
Okay here is a summary of my knowledge about Jetbrains Products and EAPs:

1. Every Product has a build number e.g. `171.4249.3`.
2. A stable version e.g. `2017.1.2` is an alias for a build number and the download URL looks like this: `https://download.jetbrains.com/webide/PhpStorm-2017.1.2.dmg`. As we experienced recently, the underlying Image may be swapped.
3. An EAP version has no alias and uses the build number: e.g. `https://download.jetbrains.com/webide/PhpStorm-EAP-171.4073.14.dmg`
4. Old versions MAY disappear. If you have a look at https://data.services.jetbrains.com/products?code=PS you will see that the last EAP version referenced in the PhpStorm formula is not listed anymore, while others are.

Generally a release for jetbrains SEEMS to work like this:
1. stable version `2016.3:100.XXXX.XXX`
2. eap version comes out: `2017.1:110.XXXX.XXX` (maybe more eap versions follow)
3. stable version comes out `2017.1:110.YYYY.YYY` 
4. bug fixes released: `2017.1.1:110.YYYY.YYZ`
5. eap version comes out: `2017.2:120.XXXX.XXX`

My advice for Jetbrains Users would be:
1. Install and use only stable versions (with or without homebrew)
2. If you want to use EAPs, install a stable version and change the update setting to EAP: <img width="591" alt="screen shot 2017-04-18 at 14 21 35" src="https://cloud.githubusercontent.com/assets/2906107/25130558/e3ba14e4-2442-11e7-95ab-94c8a98031c8.png">

As for EAP in homebrew-versions. I see three different approaches here:

1. Leave it as is and deal with broken downloads if someone "complains" and creates an issue by linking to this discussion.
2. If a new stable versions comes out with a higher build number than the last EAP (Like `171.4249.3 stable > 171.4073.14 EAP` currently at PhpStorm), update the cask in homebrew-versions to the stable version. I could update the @jcbot to do that.
3. Drop eap formulas of jetbrains products. Actually I would prefer that, as it is the least amount of work 😆

**Comment by vitorgalvao** [comment]
@leipert Thank you for the detailed explanation.

Option 2 is what we usually do, but these do change at an insane pace, and since you can change the channel from inside the app, I wouldn’t be opposed to option 3. Will open a discussion issue.

**Comment by vitorgalvao** [comment]
https://github.com/caskroom/homebrew-cask/issues/32521.

**Comment by vitorgalvao** [comment]
Thank you for sparking the discussion, @geekish. As per https://github.com/caskroom/homebrew-cask/issues/32521 we decided to remove all EAP versions, so to use them via HBC you should now download the stable version and then change the update channel from within the app.

Thank you to everyone who participated in the conversation.
