### ISSUE TITLE
[Q] How to retrieve install link dynamically?

### ISSUE THREAD

**Issue by ebraminio** [caskroom/homebrew-versions#3750]
For having a more updated WebKit, currently I am using [this formula](https://gist.github.com/ebraminio/5f824cca89d76f529974d27bc22b1cc4) that fetches WebKit download page and extracts recent version of WebKit directly from the page but fetching the link seems like not be a good idea, how is possible lazy evaluate the link on this formula and is there any other way for downloading a link on a formula? If these be solved I will try to PR the formula to this repo thats why I reported it here. Thanks

**Comment by vitorgalvao** [comment]
That‘s absolutely the wrong approach. You should be using a [`url do` block](https://github.com/caskroom/homebrew-cask/blob/master/doc/cask_language_reference/stanzas/url.md#using-a-block-to-defer-code-execution).

You can get the final result of any stanza by using `_stanza`. As an example to get the final `url` on that cask: `brew cask _stanza url 'https://gist.githubusercontent.com/ebraminio/5f824cca89d76f529974d27bc22b1cc4/raw/7bf634976b81af6b187edf77ecea0f44a1d84753/webkit-nightly.rb'`.
