### ISSUE TITLE
java9-beta.rb uses wrong paths

### ISSUE THREAD

**Issue by Vloeck** [caskroom/homebrew-versions#3973]
When you install java9-beta, the package installer puts it in 
`/Library/Java/JavaVirtualMachines/jdk-9.jdk/` 
which does not match the path in the recipe
`/Library/Java/JavaVirtualMachines/jdk#{version.minor}.jdk/`
so any actions are operated on 
`/Library/Java/JavaVirtualMachines/jdk9.jdk/` (without the -)

Additionally, the recipe wants to symlink to
`Contents/Home/jre/lib/server/libjvm.dylib`
which is now located in 
`Contents/Home/lib/server/libjvm.dylib` (without jre/)

**Comment by miccal** [comment]
https://github.com/caskroom/homebrew-versions/pull/3976
