### ISSUE TITLE
Cask request: Forklift 2

### ISSUE THREAD

**Issue by sebastienbarre** [caskroom/homebrew-versions#4055]
Hello
Would Forklift 2 be a candidate for homebrew-versions?
There are only 2 major version for the popular Forklift app, 2.x and 3.x.
I've used the app for years, but there are too many deal-breakers in 3.x for me to upgrade from 2.x.
Thanks

**Comment by commitay** [comment]
https://github.com/caskroom/homebrew-versions/pull/4057

**Comment by sebastienbarre** [comment]
Sorry about that, I did a search in the issues, including the closed ones, but nothing came back. Didn't think of checking the PRs.
