### ISSUE TITLE
Tunnelblick-beta change versioning scheme

### ISSUE THREAD

**Issue by 404NetworkError** [caskroom/homebrew-versions#4517]
Suggestion:
Change the versioning scheme for [Tunnelblick-beta](https://github.com/caskroom/homebrew-versions/blob/master/Casks/Tunnelblick-beta.rb) to follow the stable [Tunnelblick](https://github.com/caskroom/homebrew-cask/blob/master/Casks/tunnelblick.rb) cask since both the stable and beta [releases](https://github.com/Tunnelblick/Tunnelblick/releases) are hosted on GitHub.

It would look something like this for latest release at this time:
`version '3.7.3beta03,4870'`
and
`url "https://github.com/Tunnelblick/Tunnelblick/releases/download/v#{version.before_comma}/Tunnelblick_#{version.before_comma}_build_#{version.after_comma}.dmg"`

**Comment by commitay** [comment]
Feel free to send a PR.
