### ISSUE TITLE
Name of formula firefoxdeveloperedition

### ISSUE THREAD

**Issue by franklinyu** [caskroom/homebrew-versions#4519]
I think `firefox-developer-edition` looks better than this? Also `firefox-nightly`, so that all Firefox versions align:

 - `firefox`
 - `firefox-beta`
 - `firefox-developer-edition`
 - `firefox-nightly`
 - `firefox-esr`

**Comment by commitay** [comment]
`firefoxdeveloperedition` follows the [token reference](https://github.com/caskroom/homebrew-cask/blob/master/doc/cask_language_reference/token_reference.md)
