### ISSUE TITLE
Palemoon fails to install

### ISSUE THREAD

**Issue by fardjad** [caskroom/homebrew-versions#4547]
#### General troubleshooting steps

- [x] I have checked the instructions for [reporting bugs](https://github.com/caskroom/homebrew-cask#reporting-bugs) (or [making requests](https://github.com/caskroom/homebrew-cask#requests)) before opening the issue.
  - [x] None of the templates was appropriate for my issue, or I’m not sure.
- [x] I ran `brew update-reset && brew update` and retried my command.
- [x] I ran `brew doctor`, fixed as many issues as possible and retried my command.
- [x] I understand that [if I ignore these instructions, my issue may be closed without review](https://github.com/caskroom/homebrew-cask/blob/master/doc/faq/closing_issues_without_review.md).

#### Description of issue

Installing **Palemoon** throws the following error (on a case-sensitive FS):

> Error: It seems the App source '/usr/local/Caskroom/palemoon/27.5.0/PaleMoon.app' is not there.

I manually downloaded the DMG and looks like the app directory name is **Palemoon.app** but in the formula, the app stanza argument is **PaleMoon.app**.

Just to confirm this, I manually edited the formula and replaced the line `app 'PaleMoon.app'` with `app 'Palemoon.app'` and the problem was solved.

#### Output of your command with `--verbose --debug`

N/A

#### Output of `brew cask doctor`

N/A

**Comment by commitay** [comment]
Feel fee to send a PR.
