### ISSUE TITLE
Suggestion - add skype7

### ISSUE THREAD

**Issue by edrozenberg** [caskroom/homebrew-versions#4695]
#### General troubleshooting steps

- [X] I have retried my command with `--force` and the issue is still present.
- [X] I have checked the instructions for [reporting bugs](https://github.com/caskroom/homebrew-cask#reporting-bugs) (or [making requests](https://github.com/caskroom/homebrew-cask#requests)) before opening the issue.
  - [X] None of the templates was appropriate for my issue, or I’m not sure.
- [X] I ran `brew update-reset && brew update` and retried my command.
- [X] I ran `brew doctor`, fixed as many issues as possible and retried my command.
- [X] I understand that [if I ignore these instructions, my issue may be closed without review](https://github.com/caskroom/homebrew-cask/blob/master/doc/faq/closing_issues_without_review.md).

#### Description of issue

The cask for skype has been updated to skype v. 8.x.x. IMHO Skype v8 is ugly, clunky, has gross gradients, and the scrollbars don't rubberband because they are doing some kind of custom c*ap in their app. The plague of the redesigned iPhone Skype is now infecting the Mac.

For this reason I suggest having a skype7 version available so users can easily revert to a Skype that isn't horrible. Skype v7 is still the default download at https://www.skype.com/en/download-skype/skype-for-mac/downloading/

#### Output of your command with `--verbose --debug`

```
Not applicable. This is not a bug report.
```

#### Output of `brew cask doctor`

```
==> Homebrew-Cask Version
Homebrew-Cask 1.3.6
caskroom/homebrew-cask (git revision a14844; last commit 2017-11-01)
==> Homebrew-Cask Install Location
<NONE>
==> Homebrew-Cask Staging Location
/usr/local/Caskroom
==> Homebrew-Cask Cached Downloads
~/Library/Caches/Homebrew/Cask (52 files, 2.2GB)
==> Homebrew-Cask Taps:
/usr/local/Homebrew/Library/Taps/caskroom/homebrew-cask (3785 casks)
/usr/local/Homebrew/Library/Taps/caskroom/homebrew-drivers (131 casks)
/usr/local/Homebrew/Library/Taps/caskroom/homebrew-versions (175 casks)
==> Contents of $LOAD_PATH
/usr/local/Homebrew/Library/Homebrew/cask/lib
/usr/local/Homebrew/Library/Homebrew
/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.3/lib/ruby/gems/2.3.0/gems/did_you_mean-1.0.0/lib
/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.3/lib/ruby/site_ruby/2.3.0
/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.3/lib/ruby/site_ruby/2.3.0/x86_64-darwin9.0
/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.3/lib/ruby/site_ruby/2.3.0/universal-darwin9.0
/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.3/lib/ruby/site_ruby
/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.3/lib/ruby/vendor_ruby/2.3.0
/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.3/lib/ruby/vendor_ruby/2.3.0/x86_64-darwin9.0
/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.3/lib/ruby/vendor_ruby/2.3.0/universal-darwin9.0
/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.3/lib/ruby/vendor_ruby
/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.3/lib/ruby/2.3.0
/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.3/lib/ruby/2.3.0/x86_64-darwin9.0
/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.3/lib/ruby/2.3.0/universal-darwin9.0
==> Environment Variables
LANG="en_US.UTF-8"
PATH="~/.composer/vendor/bin:/usr/local/sbin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Applications/VMware Fusion.app/Contents/Public:/Applications/Wireshark.app/Contents/MacOS:/usr/local/Homebrew/Library/Taps/homebrew/homebrew-services/cmd:/usr/local/Homebrew/Library/Homebrew/shims/scm"
SHELL="/bin/bash"
```

**Comment by edrozenberg** [comment]
The latest v7 which I just downloaded from the skype website is ```Skype_7.59.37.dmg```

**Comment by edrozenberg** [comment]
To stay on v7 users may also need to disable the checkbox in Skype prefs General that says "Always keep Skype up to date"

**Comment by commitay** [comment]
> https://github.com/caskroom/homebrew-versions#acceptable-casks
> Refuse legacy versions of gratis or open-source software, unless there is a clear demonstrable need for them.

I'd suggest [creating your own tap.](https://github.com/Homebrew/brew/blob/master/docs/How-to-Create-and-Maintain-a-Tap.md)

**Comment by edrozenberg** [comment]
I'll look into a custom tap thanks. Some kind of horrible tasteless alien is at the Skype design helm and I need to escape at all costs.

**Comment by pavel-sakun** [comment]
+5 to this (me and my colleagues). New Skype look terrible, it would be cool to have a clean way to stick to classic one. Here is the cask for this, let me know if PR is needed: https://github.com/pavel-sakun/homebrew-versions/commit/8a077d16d9bb08401b802bc358876b1978d450d7

**Comment by pavel-sakun** [comment]
Just in case it won't make it's way to this repository, here is my tap with cask for Skype classic: https://github.com/pavel-sakun/homebrew-versions

**Comment by edrozenberg** [comment]
Thanks @pavel-sakun will definitely try out that formula. Wish there was a way to roll back the horrible new iPhone Skype also.

**Comment by edrozenberg** [comment]
This explains a lot about the sh*t that v8 is made of.

Craig Hockenberry (@chockenberry)2017-11-15, 10:13$ ls “/Applications/Skype.app/Contents/Frameworks/Electron Framework.framework” Yay.
--
via Tweetbot

**Comment by pavel-sakun** [comment]
Discovered that week ago, but...slack is built with it as well and the difference is just enormous.

**Comment by commitay** [comment]
https://github.com/caskroom/homebrew-versions/pull/4829#issuecomment-349810856
