### ISSUE TITLE
Suggestion for having a VLC 2 due to some VLC 3 issues

### ISSUE THREAD

**Issue by edrozenberg** [caskroom/homebrew-versions#5386]
#### General troubleshooting steps

- [x] I have retried my command with `--force` and the issue is still present.
- [x] I have checked the instructions for [reporting bugs](https://github.com/caskroom/homebrew-cask#reporting-bugs) (or [making requests](https://github.com/caskroom/homebrew-cask#requests)) before opening the issue.
  - [ ] None of the templates was appropriate for my issue, or I’m not sure.
- [x] I ran `brew update-reset && brew update` and retried my command.
- [x] I ran `brew doctor`, fixed as many issues as possible and retried my command.
- [x] I understand that [if I ignore these instructions, my issue may be closed without review](https://github.com/caskroom/homebrew-cask/blob/master/doc/faq/closing_issues_without_review.md).

#### Description of issue
I have a number of problems with VLC 3 that have made me do a manual roll-back to VLC 2:
* When VLC 3 starts it sometimes changes the brightness on my iMac 5k slightly (weird but true)
* VLC3 often sets the video window window to one size xxx X yyy, then after a short pause re-adjusts the video window size again. Clunky.
* Feels kinda glitchy in a few other small ways.
* VLC 3 takes a noticeably longer time than VLC 2 before a video actually starts playing. "Just get on with playing the video already" often comes to mind when using VLC 3.

VLC has for decades been a player that plays everything, with a UI that never quite gets it right. Never quite native, has 2 sets of preferences, kinda fugly overall, always insists on plopping up a "playlist window" before getting on with the job of playing the video.

Even so VLC 3 is a step further backward compared to VLC 2. IMHO of course.

#### Output of your command with `--verbose --debug`

```
$ brew cask info vlc
vlc: 3.0.1
https://www.videolan.org/vlc/
Not installed
From: https://github.com/caskroom/homebrew-cask/blob/master/Casks/vlc.rb
==> Name
VLC media player
==> Artifacts
VLC.app (App)
/usr/local/Caskroom/vlc/3.0.1/vlc.wrapper.sh -> vlc (Binary)
```

#### Output of `brew cask doctor`

```
==> Homebrew-Cask Version
Homebrew-Cask 1.5.10-22-gcb6828d
caskroom/homebrew-cask (git revision a8ccf; last commit 2018-03-16)
==> macOS
10.13.4
==> SIP
Enabled
==> Java
9.0.4
==> Homebrew-Cask Install Location
<NONE>
==> Homebrew-Cask Staging Location
/usr/local/Caskroom
==> Homebrew-Cask Cached Downloads
~/Library/Caches/Homebrew/Cask (71 files, 3.3GB)
==> Homebrew-Cask Taps:
/usr/local/Homebrew/Library/Taps/caskroom/homebrew-cask (3935 casks)
/usr/local/Homebrew/Library/Taps/pavel-sakun/homebrew-versions (1 cask)
/usr/local/Homebrew/Library/Taps/caskroom/homebrew-drivers (145 casks)
/usr/local/Homebrew/Library/Taps/caskroom/homebrew-versions (173 casks)
==> Contents of $LOAD_PATH
/usr/local/Homebrew/Library/Homebrew/cask/lib
/usr/local/Homebrew/Library/Homebrew
/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.3/lib/ruby/gems/2.3.0/gems/did_you_mean-1.0.0/lib
/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.3/lib/ruby/site_ruby/2.3.0
/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.3/lib/ruby/site_ruby/2.3.0/x86_64-darwin9.0
/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.3/lib/ruby/site_ruby/2.3.0/universal-darwin9.0
/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.3/lib/ruby/site_ruby
/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.3/lib/ruby/vendor_ruby/2.3.0
/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.3/lib/ruby/vendor_ruby/2.3.0/x86_64-darwin9.0
/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.3/lib/ruby/vendor_ruby/2.3.0/universal-darwin9.0
/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.3/lib/ruby/vendor_ruby
/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.3/lib/ruby/2.3.0
/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.3/lib/ruby/2.3.0/x86_64-darwin9.0
/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.3/lib/ruby/2.3.0/universal-darwin9.0
==> Environment Variables
LC_ALL="en_US.UTF-8"
PATH="/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/Homebrew/Library/Homebrew/shims/scm"
SHELL="/bin/bash"
```

**Comment by commitay** [comment]
> https://github.com/caskroom/homebrew-versions#acceptable-casks
> Refuse legacy versions of gratis or open-source software, unless there is a clear demonstrable need for them.

I'd suggest [creating your own tap.](https://github.com/Homebrew/brew/blob/master/docs/How-to-Create-and-Maintain-a-Tap.md)

That said, if we get multiple requests we might add it to this repo.

> expected to be used by a reasonable number of people
