### ISSUE TITLE
Trying to clarify/understand "acceptable" cask. 

### ISSUE THREAD

**Issue by OranguTech** [caskroom/homebrew-versions#5438]
#### General troubleshooting steps

N/A

#### Description of issue

https://github.com/caskroom/homebrew-versions#acceptable-casks says "Refuse legacy versions of gratis or open-source software, unless there is a clear demonstrable need for them."

What is "demonstrable need"?

In my particular case, I'm interested in older versions of puppet-agent as I'm using it for language checking plugin while configuring puppet manifests i different environment. Checked here first, thought I might see if others would want it.

**Comment by commitay** [comment]
> What is "demonstrable need"?

The newer version is broken and/or missing features that were previously included.

> caskroom/versions is not intended to be used for all and any old versions you personally require for xyz project; casks submitted here should be expected to be used by a reasonable number of people and supported by contributors long-term.

Note that the above also applies, we would need multiple requests before we would consider adding it to this repo.
