### ISSUE TITLE
Travis false positives

### ISSUE THREAD

**Issue by rolandwalker** [caskroom/homebrew-versions#632]
Per #630, Travis in this repo is returning green when tests should fail.

Presumably this is also true in the fonts and unofficial repos.

Update: one issue is that `method_missing` warnings still pass audit.  This bug affects all repos.  See https://travis-ci.org/caskroom/homebrew-versions/jobs/44680345 .

**Comment by vitorgalvao** [comment]
Is this still the case? #646 is failing, and it seems like Travis making a mistake, in that case.

**Comment by rolandwalker** [comment]
#646 was failing because of something I forgot, fixed in #647.

I've updated the title of this issue.  I was mistaken that Travis *always* passes, but (as the update says) `method_missing` warnings do pass audit, which is wrong.

**Comment by vitorgalvao** [comment]
It seems like we’re having false negatives as well (#652, #654).

**Comment by fanquake** [comment]
We can reopen this if issues reappear.
