### ISSUE TITLE
wireshark-dev url returns 404

### ISSUE THREAD

**Issue by xen0l** [caskroom/homebrew-versions#657]
http://www.wireshark.org/download/osx/Wireshark%201.99.0%20Intel%2064.dmg is not available.  We should use https://www.wireshark.org/download/automated/osx/Wireshark%201.99.2-617-g74b20dc%20Intel%2064.dmg instead.

**Comment by radeksimko** [comment]
Good catch, thanks, will you send pull-request to update the cask?

**Comment by xen0l** [comment]
```
cask :v1 => 'wireshark-dev' do
  version '1.99.2-617-g74b20dc'
  sha256 '093e73cc1b755d3c2cae9f5647bfb5aad2cd22d48549cb44a353467f61116684'

  url "https://www.wireshark.org/download/automated/osx/Wireshark%20#{version}%20Intel%2064.dmg"
  homepage 'http://www.wireshark.org'
  license :unknown

  pkg "Wireshark #{version} Intel 64.pkg"
  uninstall :pkgutil => 'org.wireshark.*'
end
```

The only problem with this is that is has to be updated quite often. I haven't found a better solution.

**Comment by radeksimko** [comment]
It's expectable that a dev version has to be updated often, that's why is it part of `homebrew-versions` repository and not the main `homebrew-cask`.

Attaching code is helpful, but [sending an actual PR](https://help.github.com/articles/creating-a-pull-request/) would be even more helpful. ;-)

**Comment by vitorgalvao** [comment]
Thank you for the head-up, @xen0l. Will be updated in #658. The cask you’ve submitted posted doesn’t work, by the way.
