### ISSUE TITLE
Spotifybeta cask is broken

### ISSUE THREAD

**Issue by zchee** [caskroom/homebrew-versions#745]
[Spotifybeta](https://github.com/caskroom/homebrew-versions/blob/master/Casks/spotifybeta.rb) cask is broken.

Now, I typed

    $ brew cask install spotifybeta

to result,

    ==> Downloading http://download.spotify.com/beta/spotify-app-1.0.0.909.ge4845795-1223.dmg
    ######################################################################## 100.0%
    ==> This subcommand requires root privileges: bsexec
    Error: Empty plist input

What's happend ?
I think the error is to blame for this line.
https://github.com/caskroom/homebrew-versions/blob/master/Casks/spotifybeta.rb#L13
But, I do not know how to fix.

**Comment by vitorgalvao** [comment]
No, that’s unrelated. It seems you might be experiencing a recent issue, fixed in https://github.com/caskroom/homebrew-cask/pull/9491. Please `brew update && brew upgrade brew-cask && brew cleanup && brew cask cleanup` and try again.

**Comment by zchee** [comment]
This issue already answered phinze on IRC.
brew upgrade was after install passed.
thanks.
