### ISSUE TITLE
Add Java8 beta (8u60+)

### ISSUE THREAD

**Issue by radeksimko** [caskroom/homebrew-versions#831]
The latest beta is currently `8u60` and it has completely different packaging and installation from the previous versions.
https://derflounder.wordpress.com/2015/03/06/macjreinstaller-and-oracles-java-install-application/

It will require some extra care, most likely some different hacks etc.

I think I managed to do the installation bit [here](https://github.com/caskroom/homebrew-versions/blob/b25f6a123dd2fa7a54faf1f6a2e29d73071ae78c/Casks/java8-beta.rb), but I'm struggling to make it work with the latest Android Studio.

I think I'll need to have a look again to how/where does app like Android Studio looks for different Java versions.

**Comment by adityadalal924** [comment]
Fixed in https://github.com/caskroom/homebrew-versions/issues/1425
